CREATE TABLE IF NOT EXISTS calculation_result
(
    calc_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_number  INT           NOT NULL,
    second_number INT           NOT NULL,
    operation     VARCHAR(32)   NOT NULL,
    result        BIGINT        NOT NULL
);